### ISSUE TITLE
通过 IOS 添加配件失败

### ISSUE THREAD

**Issue by freemanke** [TripleView/HomeKit.Net#1]
通过直接运行 deom，通过 iphone 添加配件一直显示正在设置，最后显示无法添加配件
![IMG_5329](https://github.com/TripleView/HomeKit.Net/assets/1439128/cba55c42-3cce-4dbd-ae96-474e58e3e3c8)
![IMG_5328](https://github.com/TripleView/HomeKit.Net/assets/1439128/5e8d48bc-d489-4481-9050-7bd89055b48b)

**Comment by TripleView** [comment]
控制台的日志发出来看下

**Comment by freemanke** [comment]
<img width="738" alt="image" src="https://github.com/TripleView/HomeKit.Net/assets/1439128/880088d2-b6a6-41aa-8f1c-567a156d2f66">

**Comment by TripleView** [comment]
通过邮件以及微信沟通，确认导致该问题的原因是因为用户手机连接了vpn导致与配件不在同一个局域网导致，关闭vpn后即可正常连接。
